var background = chrome.extension.getBackgroundPage();
var apiKey = '5bcf0511a506d8d2a6d2141eeb404edc';
var successURL = 'http://benhiller.github.com/success.html';
var cancelURL = 'http://www.facebook.com/connect/login_failure.html';
var permissions = 'read_stream,publish_stream,offline_access,read_mailbox';
var loginURL = 'http://www.facebook.com/login.php?api_key=' + apiKey +
                '&fbconnect=true' +
                '&v=1.0' +
                '&connect_display=page' +
                '&return_session=true' +
                '&session_key_only=true' +
                '&next=' + successURL +
                '&cancel_url=' + cancelURL +
                '&req_perms=' + permissions;
var refreshTime = 1000 * 5 * 60;
var commentText = chrome.i18n.getMessage("comment");
var unlikeText = chrome.i18n.getMessage("unlike");
var likeText = chrome.i18n.getMessage("like");
var statusFillerText = chrome.i18n.getMessage("statusFiller");
var shareText = chrome.i18n.getMessage("share");
var logoutText = chrome.i18n.getMessage("logout");
var errorText = chrome.i18n.getMessage("error");
var likesThisText = chrome.i18n.getMessage("likesThis");
var likeThisText = chrome.i18n.getMessage("likeThis");
var someoneText = chrome.i18n.getMessage("someone");
var commentFillerText = chrome.i18n.getMessage("commentFiller");
var loginButtonText = chrome.i18n.getMessage("loginButton");
var introText = chrome.i18n.getMessage("intro");
var viewAllText = chrome.i18n.getMessage("viewAll");
var commentsText = chrome.i18n.getMessage("comments");
